config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { :registrations => "user_registrations" }

  resources :products do
    resources :comments
  end
  
  resources :users
  
  get 'static_pages/about'

  get 'static_pages/contact'
  
  post 'static_pages/thank_you'

  get 'static_pages/index'
  
  get 'static_pages/landing_page'
  
  post 'payments/create'
  
  mount ActionCable.server => '/cable'
  

  root 'static_pages#index'

  resources :orders, only: [:index, :show, :create, :destroy]
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :comments
  has_many :orders
  
  def highest_rating_comment
  comments.rating_desc.first
  end
  
  def lowest_rating_comment
  comments.rating_asc.first
  end
  
  def average_rating
  comments.average(:rating).to_f
  end

  validates :name, presence: true

 
end
  

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      #byebug
      search_term = params[:q]
      if Rails.env.production?
        @products = Product.where("name ilike ?", "%#{search_term}%").paginate(:page => params[:page], :per_page => 3)
    else
        @products = Product.where("name LIKE ?", "%#{search_term}%").paginate(:page => params[:page], :per_page => 3)
    end  
    else
      @products = Product.all.paginate(:page => params[:page], :per_page => 3)
    end  
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
    
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to :products, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/ _comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
    <div class="row">
    <hr>
          
          <p><div class="rated" data-score="<%= comment.rating %>"></div></p>
          <p><%= comment.body %></p>
            
            <p>
              <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
              <% if signed_in? && current_user.admin? %>
                <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </p>

        </div>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
  <%= f.label :colour %><br>
  <%= f.text_field :colour %>
  </div>
  <div class="field">
  <%= f.label :price %><br>
  <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
 
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
  
  <% cache product do %>
    <div class="col-sm-4 col-xs-12">
      <h1><%= product.name %></h1>
      <%= image_tag(product.image_url, class: "img-responsive")%>
      <h5><%= product.description %></h5>
      <h5><strong><%= product.price%> $</strong><br></h5>
      <td><%= link_to 'Show', product %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </div><!-- /col -->  
  <% end %>
  
    

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<div class="form">
<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>


<div class="container-fluid">
  
        <div class="pages"><%= will_paginate @products %></div>
  
  <div class="row">
    <% cache(cache_key_for_products) do %>
      <%= render @products %>
    <% end %>
  </div>  
</div>
<br>

<h4><%= link_to 'New Product', new_product_path %></h4>

app/views/products/new.html.erb
<h1>New Product</h1>

<div class="form">
<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="row" data-product-id="<%= @product.id %>">
    <div class="col-md-12">
      <div>
        <%= image_tag(@product.image_url, width: "350", class: "img-responsive img-zoom", data_zoom_image: "@product.image_url")%>
      </div>
    </div>
  
    <div class="col-md-12">
      <p>
        Average Rating: <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>">
      </p>
    </div>
    
    
    
    <div class="col-md-12">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>
    </div>
    
    <div class="col-md-12">
      <p>
        <strong>Description:</strong>
        <%= @product.description %>
      </p>
    </div>
    
    <div class="col-md-12">
      <p>
        <strong>Colour:</strong>
        <%= @product.colour %>
      </p>
    </div>
  
    <div class="col-md-12">
      <p>
        <strong>Price:</strong>
        <%= @product.price %>
      </p>
    </div>
    
    <%= form_tag "/payments/create" do %>
          <%= hidden_field_tag(:product_id, @product.id) %>
          <%= render partial: "shared/stripe_checkout_button" %>
        <% end %>
    
    <div class="col-md-12">
      <%= render "products/new_comment" %>
    </div>
  
  <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>

    <div class="col-md-12">
      <%= render "products/comments" %>  
    </div>
    
    <div class="pages"><%= will_paginate @comments %></div>

</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>